### ISSUE TITLE
hydratool failed to start due to plugin xcb

### ISSUE THREAD

**Issue by FdLSifu** [hydrabus/hydratool#1]
I am getting an issue when I run hydratool.
Here is the error:
_./hydratool_  
_This application failed to start because it could not find or load the Qt platform plugin "xcb"
in ""._

_Reinstalling the application may fix this problem._
_zsh: abort (core dumped)  ./hydratool_

I am running arch linux 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux.
Here the ldd output:
ldd hydratool  
	linux-vdso.so.1 (0x00007ffd3c5f9000)
	libQt5Widgets.so.5 => /usr/lib/libQt5Widgets.so.5 (0x00007f44238a2000)
	libQt5Gui.so.5 => /usr/lib/libQt5Gui.so.5 (0x00007f442312c000)
	libQt5SerialPort.so.5 => /usr/lib/libQt5SerialPort.so.5 (0x00007f4422f14000)
	libQt5Core.so.5 => /usr/lib/libQt5Core.so.5 (0x00007f442281f000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007f4422497000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007f4422280000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007f4421eda000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007f4421cbc000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007f44219aa000)
	libGL.so.1 => /usr/lib/libGL.so.1 (0x00007f442171f000)
	libpng16.so.16 => /usr/lib/libpng16.so.16 (0x00007f44214e9000)
	libharfbuzz.so.0 => /usr/lib/libharfbuzz.so.0 (0x00007f4421251000)
	libz.so.1 => /usr/lib/libz.so.1 (0x00007f442103a000)
	libudev.so.1 => /usr/lib/libudev.so.1 (0x00007f44242b0000)
	libicui18n.so.59 => /usr/lib/libicui18n.so.59 (0x00007f4420bbc000)
	libicuuc.so.59 => /usr/lib/libicuuc.so.59 (0x00007f442080b000)
	libsystemd.so.0 => /usr/lib/libsystemd.so.0 (0x00007f4424228000)
	libpcre2-16.so.0 => /usr/lib/libpcre2-16.so.0 (0x00007f442059c000)
	libdouble-conversion.so.1 => /usr/lib/libdouble-conversion.so.1 (0x00007f442038c000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x00007f4420188000)
	libglib-2.0.so.0 => /usr/lib/libglib-2.0.so.0 (0x00007f441fe75000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f44240fa000)
	libGLX.so.0 => /usr/lib/libGLX.so.0 (0x00007f441fc43000)
	libX11.so.6 => /usr/lib/libX11.so.6 (0x00007f441f904000)
	libXext.so.6 => /usr/lib/libXext.so.6 (0x00007f441f6f2000)
	libGLdispatch.so.0 => /usr/lib/libGLdispatch.so.0 (0x00007f441f43c000)
	libfreetype.so.6 => /usr/lib/libfreetype.so.6 (0x00007f441f175000)
	libgraphite2.so.3 => /usr/lib/libgraphite2.so.3 (0x00007f441ef49000)
	libresolv.so.2 => /usr/lib/libresolv.so.2 (0x00007f441ed33000)
	libcap.so.2 => /usr/lib/libcap.so.2 (0x00007f441eb2f000)
	librt.so.1 => /usr/lib/librt.so.1 (0x00007f441e927000)
	libicudata.so.59 => /usr/lib/libicudata.so.59 (0x00007f441ce14000)
	liblzma.so.5 => /usr/lib/liblzma.so.5 (0x00007f441cbee000)
	liblz4.so.1 => /usr/lib/liblz4.so.1 (0x00007f441c9da000)
	libgcrypt.so.20 => /usr/lib/libgcrypt.so.20 (0x00007f441c6cc000)
	libgpg-error.so.0 => /usr/lib/libgpg-error.so.0 (0x00007f441c4b7000)
	libpcre.so.1 => /usr/lib/libpcre.so.1 (0x00007f441c244000)
	libxcb.so.1 => /usr/lib/libxcb.so.1 (0x00007f441c01b000)
	libbz2.so.1.0 => /usr/lib/libbz2.so.1.0 (0x00007f441be0b000)
	libXau.so.6 => /usr/lib/libXau.so.6 (0x00007f441bc07000)
	libXdmcp.so.6 => /usr/lib/libXdmcp.so.6 (0x00007f441ba01000)

**Comment by bvernoux** [comment]
Could you check those solutions:
https://askubuntu.com/questions/308128/failed-to-load-platform-plugin-xcb-while-launching-qt5-app-on-linux-without
Note: I have tested hydratool using Qt5 static build in order to avoid such problem I plan to release the static Qt5.x binary for Windows7(MSVC2013) & Ubuntu 16.x LTS

**Comment by FdLSifu** [comment]
Hi,

I figure out how to launch the tool. I just removed qt.conf from the project and everything is WORKING!!

Thanks

**Comment by bvernoux** [comment]
I have removed the qt.conf from the project like that this problem shall not happen anymore
Thanks for the feedback
